### ISSUE TITLE
Client upload

### ISSUE THREAD

**Issue by ghost** [jaller200/LUNIServerProject#19]
Like @rioforce said, I think we need to upload the LU Client on the Git. No re-branding like Nexus2 or something...

Also, should we upload it as a folder, .zip, or .rar?

**Comment by ghost** [comment]
Well, the client is going to be Tim's anyhow, as it's the only one that completely works. Not completely sure why that needs to happen, as we're not editing it or need to directly read the files. It's an independent application.

If you're going to upload it though, zip it. It's smaller, and we don't need to work with the contents.

**Comment by ghost** [comment]
Okay, I'll upload it right now.

**Comment by ghost** [comment]
Are you planning to upload it to this repo? It's quite large, you know. Also, which version?

**Comment by jaller200** [comment]
Wait... Upload the client? It's like 3GB zipped or 10GB unzipped. I would not advise uploading it here unless you compress it with max compression (such as .7z) - max upload here should be around 1-2GB (if that). That's mainly because we are not editing the client at all, so it is static, not dynamic.

**Comment by ghost** [comment]
Yeah, I'd imagine what's in the GitHub would really need to be anything of which the source would need to be changed, a dependency for such, or possibly viewed (ie the RakNet folder).

**Comment by guy1853** [comment]
Getting on to that right now :]

**Comment by ghost** [comment]
Doesn't GitHub have a 100 megabyte file size limit?

**Comment by ghost** [comment]
Probably... hence @guy1853 had trouble uploading.

**Comment by ghost** [comment]
Shouldn't this be closed due to its failure?

**Comment by ghost** [comment]
Yep. It'll probably be hosted on the site once it's up as a mirror for your's @Timtech.
