### ISSUE TITLE
Client not communicating with server

### ISSUE THREAD

**Issue by blakeearth** [jaller200/LUNIServerProject#30]
I'm using an external IP address in both with the necessary ports forwarded (1001, 2002, 2003, 2004). The server is successful in connecting to my MySQL and I can register users.

I have tried using localhost for both the client and server as well. I get the same result: "Connecting to Authentication" --> "Sorry!"

I hope I'm not doing something stupid...

**Comment by blakeearth** [comment]
I know this project is mostly abandoned; I'm just crossing my fingers that someone knows whether it's something I'm doing wrong. I cannot find anyone else with this issue.

**Comment by blakeearth** [comment]
I'm sorry to spam everyone. While the server was booting up and connecting to MySQL, it was not starting to listen for CHAR, WORLD, and AUTH. I think the problem may result from issues in my Visual Studio compilation. If anyone else is having the same issue I am, I recommend downloading a pre-built release from http://luniserver.com/server/0/8/0/Alpha/1/Release.zip.

Thank you!

**Comment by ghost** [comment]
I'm going to guess you didn't edit the redirect ports in config.ini (ie, here: https://github.com/jaller200/LUNIServerProject/blob/master/Source/LUNI-Unstable-Dev/Source/Debug/config.ini)

Also, this project is not only defunct, there is also a much newer version of it in this repo: https://github.com/LUNIServer/UniverseServer

**Comment by blakeearth** [comment]
Thank you for your help. I did not change the ports. I was also setting the redirect IP to my preferred server IP through my domain, universe.blake.earth, instead of my public IP. All is corrected and working properly now, and my friends can join using universe.blake.earth. I am using the version TimTech uploaded a few months ago; I have no idea where it lies in the timeline of development. Thank you very much.

**Comment by ghost** [comment]
That version was Jonny's final source, which we commonly refer to as 0.8. It's much newer than this. I'm glad you were able to get everything working thanks to Knightoffaith.
