### ISSUE TITLE
RakNet dependency

### ISSUE THREAD

**Issue by ghost** [jaller200/LUNIServerProject#5]
Is RakNet 3.25 still needed as a dependency, or is everything needed in the RakNet folder of the server?

**Comment by jaller200** [comment]
Not everything in the RakNet folder is used by the server itself, but the RakNet files the server uses in turn uses other RakNet files which in turn uses more. Also, I believe I am missing a couple of classes (Quaternion and Vector3D)...

**Comment by ghost** [comment]
I guess my real question is: is this a requirement, and as such the full folder should be included in the source, or is that unnecessary and the dependency in the code be removed, just leaving a note that if things don't work correctly to try and add it?

**Comment by ghost** [comment]
Dealt with in latest versions. Full RakNet is included in the repo, dynamically linked in project preferences.
